spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10

  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 5000

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${FRONTEND_URL}/auth/callback
  admin-key: ${KAKAO_ADMIN_KEY}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${S3_BUCKET_NAME}

frontend:
  url: ${FRONTEND_URL}

ai:
  server-url: ${AI_SERVER_URL}
mock:
  ai:
    enabled: false

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
