spring:
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moa?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10

  data:
    redis:
      host: localhost
      port: 6379

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: http://localhost:8080/api/v1/auth/login/oauth
  admin-key: ${KAKAO_ADMIN_KEY}

ai:
  server-url: ${AI_SERVER_URL}
mock:
  ai:
    enabled: true

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${S3_BUCKET_NAME}

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.filter: DEBUG
#    org.hibernate.type.descriptor.sql: trace
    com.moa.moa_server.domain.vote.service.v3: DEBUG
