spring:
  application:
    name: moa-server

jwt:
  secret: ${JWT_SECRET}

kakao:
  token-uri: https://kauth.kakao.com/oauth/token
  user-info-uri: https://kapi.kakao.com/v2/user/me
  unlink-uri: https://kapi.kakao.com/v1/user/unlink

management:
  endpoints:
    web:
      exposure:
        include: prometheus
