spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moa?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: http://localhost:8080/api/v1/auth/login/oauth